name: CI
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
 
      # Setup Python 3.12.7
      - name: Set up Python 3.12.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.10"
 
      # Install from requirements.txt
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Run as a mlflow project
      - name: Run MLflow project
        run: |
          mlflow run MLProject --env-manager=local
 
      # Upload mlruns as artifact
      - name: Upload mlruns as artifact
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-logs
          path: mlruns/
